name: quran_finder
version: 1.0.0+1
publish_to: none
description: Qur'an Finder App for Final Year Project, Authored by - Utrodus
  Said Al Baqi (Computer Science Student at UNU Blitar)
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  get: 4.6.5
  ionicons: ^0.2.2
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17
  flutter_test:
    sdk: flutter

# Run command to generate native splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/img/img_logo_splash.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
